### ISSUE TITLE
Image Flipping Broken

### ISSUE THREAD

**Issue by HelloKitty** [Jameskmonger/317refactor#18]
This fault ends up breaking probably a lot of things, but most noticeably it breaks the highlights on the UI tabs.

See: https://github.com/Jameskmonger/317refactor/blob/931192235ecbf08ea82fd131d05e6ddb4fc2bd00/src/com/jagex/runescape/IndexedImage.java#L143

assigns local pixels to itself. Should be referencing the pixels outside the scope of the method. Personally, I just rename overriding variables like that.

They also were responsible for this: https://github.com/Jameskmonger/317refactor/commit/dc99b4c46fcb3c5d164fb60ecf6bdfdfdc7b96a9

and aftew others.

**Comment by Jameskmonger** [comment]
thanks again @HelloKitty , just fixed this in dc79171

![image](https://user-images.githubusercontent.com/2037007/188009983-60031085-1614-462a-b3e2-132d5d58a23b.png)
