### ISSUE TITLE
Shading Broken

### ISSUE THREAD

**Issue by HelloKitty** [Jameskmonger/317refactor#19]
Shading bug is not present in the normal Java client or other clients, including Lins C# port. Unfortunately this is just one of several bugs introducing during the refactoring. I unfortunately forgot to raise each one as I was forced to fix them in my C# fork.

https://i.gyazo.com/3f04eccd9473acbf37b3265a300f6217.png

**Comment by HelloKitty** [comment]
Broken as far back as 7dea30fb4c1c200c3eef284b513a6cfe8e67255f

**Comment by HelloKitty** [comment]
Known to be working correctly on: 4bee7576d80a5c6308a70cefb976abf874efb52e

I will begin narrowing down between the two commits to find when it was broken.

**Comment by HelloKitty** [comment]
Broke between f628176eb99aa8e94018d28d74c3fffb39a400c8 and 0e4b71d9f434030accb0b0b2c9fc9758a4982fd5

**Comment by HelloKitty** [comment]
I spent hours determining the issue. One of many MAJOR bugs in this client that is not present in a regular 317 decompiled client.

To fix it see: https://github.com/HelloKitty/RS317.Sharp/commit/8e7b4296a4102a8686db85eae438b4d8bd2c0b3c

**Comment by Jameskmonger** [comment]
Thank you so much for investigating this @HelloKitty 

I imagine it was broken in either 6afc7b02ffe7c36005c3067e8f600ac1bfda7fe1 or 5aa64e4acaf4a32a762695061b92f2aaa89159a7 :(

**Comment by Jameskmonger** [comment]
hey @HelloKitty 

I'm closing this as I've just fixed it in https://github.com/Jameskmonger/317refactor/commit/68d8f1d56edbc4dc9070f50a6247de064e16b1d2

Thanks again for reporting ❤️ your help in finding out the broken builds was helpful
